# Generated by Django 5.1.4 on 2025-01-05 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(blank=True, max_length=200, null=True)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('data_on', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ordemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco_de_entrega', models.CharField(max_length=200)),
                ('ordenado_por', models.CharField(max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('desconto', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('subtotal', models.PositiveIntegerField(default=0)),
                ('pedido_status', models.CharField(choices=[('Pedido Recebido', 'Pedido Recebido'), ('Aguardando Pagamento', 'Aguardando Pagamento'), ('Pagamento Aprovado', 'Pagamento Aprovado'), ('Pedido Enviado', 'Pedido Enviado'), ('Pedido Entregue', 'Pedido Entregue'), ('Pedido Cancelado', 'Pedido Cancelado')], max_length=50)),
                ('data_on', models.DateField(auto_now_add=True)),
                ('kart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.kart')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('imagem', models.ImageField(upload_to='produtos')),
                ('imagem2', models.ImageField(upload_to='produtos')),
                ('imagem3', models.ImageField(upload_to='produtos')),
                ('preco_compra', models.PositiveIntegerField()),
                ('preco_venda', models.PositiveIntegerField()),
                ('descricao', models.TextField()),
                ('visualizacao', models.PositiveIntegerField(default=0)),
                ('garantia', models.CharField(blank=True, max_length=200, null=True)),
                ('devolucao', models.CharField(max_length=200)),
                ('estoque', models.PositiveIntegerField(default=0)),
                ('avaliacao', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='KartProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('subtotal', models.PositiveIntegerField(default=0)),
                ('kart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.kart')),
                ('Produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.produto')),
            ],
        ),
    ]
