# Generated by Django 5.1.4 on 2026-01-09 18:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_completo",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("endereco", models.CharField(blank=True, max_length=200, null=True)),
                ("data_on", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Kart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total", models.PositiveIntegerField(default=0)),
                ("criado_em", models.DateField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="loja.cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrdemPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("subtotal", models.PositiveIntegerField(default=0)),
                ("desconto", models.PositiveIntegerField(default=0)),
                ("total", models.PositiveIntegerField(default=0)),
                (
                    "pedido_status",
                    models.CharField(
                        choices=[
                            ("Pedido Criado", "Pedido Criado"),
                            ("Aguardando Pagamento", "Aguardando Pagamento"),
                            ("Pagamento Aprovado", "Pagamento Aprovado"),
                            ("Pedido Cancelado", "Pedido Cancelado"),
                        ],
                        db_index=True,
                        default="Aguardando Pagamento",
                        max_length=50,
                    ),
                ),
                ("metodo_pagamento", models.CharField(default="PIX", max_length=30)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("pago_em", models.DateTimeField(blank=True, null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="loja.cliente",
                    ),
                ),
                (
                    "kart",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="loja.kart"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gateway", models.CharField(default="pagarme", max_length=50)),
                ("gateway_id", models.CharField(blank=True, max_length=100, null=True)),
                ("txid", models.CharField(blank=True, max_length=100, null=True)),
                ("pix_qr_code", models.TextField(blank=True, null=True)),
                ("pix_qr_code_url", models.TextField(blank=True, null=True)),
                ("pix_expira_em", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("PAGO", "Pago"),
                            ("EXPIRADO", "Expirado"),
                            ("CANCELADO", "Cancelado"),
                            ("ERRO", "Erro"),
                        ],
                        db_index=True,
                        default="PENDENTE",
                        max_length=30,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("confirmado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "pedido",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagamento",
                        to="loja.ordempedido",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                (
                    "codigo_barras",
                    models.CharField(
                        db_index=True,
                        help_text="Código de barras / QRCode do produto",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("imagem", models.ImageField(upload_to="produtos")),
                ("imagem2", models.ImageField(upload_to="produtos")),
                ("imagem3", models.ImageField(upload_to="produtos")),
                ("preco_compra", models.DecimalField(decimal_places=2, max_digits=10)),
                ("preco_venda", models.DecimalField(decimal_places=2, max_digits=10)),
                ("descricao", models.TextField()),
                ("visualizacao", models.PositiveIntegerField(default=0)),
                ("devolucao", models.CharField(max_length=200)),
                (
                    "estoque",
                    models.PositiveIntegerField(
                        default=0, help_text="Estoque calculado a partir dos lotes"
                    ),
                ),
                ("avaliacao", models.PositiveIntegerField(default=0)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="loja.categoria"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoteProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_lote", models.CharField(blank=True, max_length=50, null=True)),
                ("quantidade", models.PositiveIntegerField()),
                ("data_vencimento", models.DateField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lotes",
                        to="loja.produto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KartProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(default=0)),
                ("total", models.PositiveIntegerField(default=0)),
                ("subtotal", models.PositiveIntegerField(default=0)),
                (
                    "kart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="loja.kart"
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="loja.produto"
                    ),
                ),
            ],
        ),
    ]
