# Generated by Django 5.1.4 on 2025-01-12 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordempedido',
            name='kart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loja.kart'),
        ),
    ]
