# Generated by Django 5.1.4 on 2025-01-12 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_alter_ordempedido_kart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kartproduto',
            old_name='Produto',
            new_name='produto',
        ),
    ]
